import Image from 'next/image';

import logo from '@/app/assets/logo.png';

export default function Home() {
  return (
    <div className="flex h-screen min-h-screen w-screen flex-col items-center justify-center px-6 text-center font-sans">
      <div className="items mb-8 flex flex-col items-center">
        <Image
          alt="Logo" // Generated by nano-banana
          className="h-60 w-auto object-contain"
          priority
          src={logo}
        />
        <div className="mt-2 mb-2 font-black text-4xl">Diana Radio FM.307</div>
        <div className="font-semibold text-base">
          An alternative frontend project for NCM Podcast@嘉心糖周报
        </div>
      </div>
      <div>施工中...</div>
    </div>
  );
}
